### ISSUE TITLE
Improve utilization of Lunr lib for better results

### ISSUE THREAD

**Issue by postb99** [poesieland/poesieland.github.io#48]
https://github.com/McShelby/hugo-theme-relearn/issues/890 willing to work on this, play with the following points.

**Analysis, thoughts and conclusions:**

- ✅ decided not to enable back stemmers because current custom search pattern currently looks for * searchedterm and searchedterm * thus I think this fits most of the needs, thinking of French, English and German word construction. 
- ✅ using default "AND" search rather than "OR": not exactly that but after studying and documenting I added different search rules for multiple term search.
- 💡Allow wildcard (but not hyphen or tilde): 
  - First thought: ok as-is for single term because current custom search pattern currently looks for *searchedterm and searchedterm*. Added function documentation.
  - Second thought: remove automatic wildcard search and let user type a star where he wants. Document it on search page.
  - Third thought: move wildcard handling into search pattern function so that: without wildcard, looks as yet for *searchedterm and searchedterm*. With wildcard: looks for the same but ensure no duplicate (in case user typed  searchedterm*) and adjust boosters when user typed * ar start or end of search term.
- ✅ Study how a word with hyphen is handled by Lunr's tokenizer. This will help me for next point. But tokenizing seems to be language independent. https://github.com/olivernn/lunr.js/blob/aa5a878f62a6bba1e8e5b95714899e17e8150b38/lib/tokenizer.js#L76
- 💡Find out how to properly lookup for "arc-en-ciel" or "est-ce", hoping this is not just a French specificity. Should be looked up as single term or exact match.
- 💡Compare performance with and without stemmers, this could be interesting to have some insight about it.

Basic information:
The lib hasn't been updated since 2020 :)

Last available version, and no fork provided some code change it seems... https://github.com/olivernn/lunr.js/tree/v2.3.9

We're up-to-date already, that's fine : https://github.com/McShelby/hugo-theme-relearn/commits/6bdf05fe968d80c9ac8b1826d746e183f2192c85/static/js/lunr.min.js?browsing_rename_history=true&new_path=static/js/lunr/lunr.min.js&original_branch=main

Interestingly, the theme's lunr language files support 25 languages, while Lunr officially ships 14 languages.

**Goals:**

- [x]  decide to keep stemmers disabled
- [x] improve multiple terms search, to be finished, move code to searchPatterns function 
- [x] improve wildcard search, allow user to type wildcard and adjust boosters in searchPatterns function depending on user's wildcard(s) position - nothing done, seems to work as is
- [x] study hyphen handling (tokernizer) : it is a word boundary
- [x] decide how to handle search with meaningful hyphens in words (French compound words).
- [ ] benchmark of search with or without stemmers => https://github.com/postb99/hugo-theme-relearn-lunr-customization/issues/2
- [ ] update search page to inform user that he can use *? I could do this since I overrided the page.
- [ ] something is wrong about building Lunr index, the article content is copied to the "description" field and this is really a waste => https://github.com/postb99/hugo-theme-relearn-lunr-customization/issues/3
- [ ] how to push "categories" article metadata to Lunr's index, as "tags" metadata is? => https://github.com/postb99/hugo-theme-relearn-lunr-customization/issues/3

**Comment by postb99** [comment]
@McShelby it looks like single term search is already fine, I added a different viewpoint for multiple terms search: exact match in this case and every term is required. This pleases me more.

More to come later.

For now I forked the theme and work on this copy.

https://github.com/McShelby/hugo-theme-relearn/commit/be7dfcb6c50d104fe7d65d778c47141d7ba217cd

**Comment by McShelby** [comment]
Btw: the documentation of supported languages on https://lunrjs.com/guides/language_support.html is outdated.

The languages are stored in a separate [repo](https://github.com/MihaiValentin/lunr-languages/tree/master/min) and were selectivly copied over by me. These should also be on the latest version.

**Comment by McShelby** [comment]
and: I already took a look at other search solutions in the past but neither of them seemed to offer such a broad support for foreign languages or were easily to integrate.

If there would be such  a solution I am also willing to replace Lunr with something better.

Requirements:

- search index must be buildable by running `hugo` only. No shell/batch/python nor node/npm
- must support "a major amout" (whatever that is ;-) ) of supported languages by the theme
- must run offline - no calls to extrenal web resources outside of the `public` folder
- must run from the file system (this is usually not a problem if the others requirements are met)

**Comment by Xarkam** [comment]
Check this https://github.com/krisk/Fuse

**Comment by McShelby** [comment]
Doesn't sound to promising as it may violate my second item from above list: https://github.com/krisk/Fuse/issues?q=is%3Aissue+language

Neither the docs, internet or the issue tracker shows that support for other languages besides English will work.

**Comment by postb99** [comment]
Follow up my further studies on my test website: https://github.com/postb99/hugo-theme-relearn-lunr-customization
